package services

import models.Currency
import util.BaseSpec

class CurrencyServiceSpec extends BaseSpec {

  private val expectedCurrencies: List[Currency] = List(
    Currency("AED", "Abu Dhabi Dirham (AED)", Some("AED")),
    Currency("AED", "Dubai Dirham (AED)", Some("AED")),
    Currency("AED", "UAE Dirham (AED)", Some("AED")),
    Currency("ALL", "Albania Lek (ALL)", Some("ALL")),
    Currency("AMD", "Armenia Dram (AMD)", Some("AMD")),
    Currency("AOA", "Angola Readj Kwanza (AOA)", Some("AOA")),
    Currency("ARS", "Argentina Peso (ARS)", Some("ARS")),
    Currency("AUD", "Australia Dollar (AUD)", Some("AUD")),
    Currency("AWG", "Aruba Florin (AWG)", Some("AWG")),
    Currency("AZN", "Azerbaijan New Manat (AZN)", Some("AZN")),
    Currency("BAM", "Bosnia- Herzegovinia Marka (BAM)", Some("BAM")),
    Currency("BBD", "Barbados Dollar (BBD)", Some("BBD")),
    Currency("BDT", "Bangladesh Taka (BDT)", Some("BDT")),
    Currency("BGN", "Bulgaria Lev (BGN)", Some("BGN")),
    Currency("BHD", "Bahrain Dinar (BHD)", Some("BHD")),
    Currency("BIF", "Burundi Franc (BIF)", Some("BIF")),
    Currency("BMD", "Bermuda Dollar (US) (BMD)", Some("BMD")),
    Currency("BND", "Brunei Dollar (BND)", Some("BND")),
    Currency("BOB", "Bolivia Boliviano (BOB)", Some("BOB")),
    Currency("BRL", "Brazil Real (BRL)", Some("BRL")),
    Currency("BSD", "Bahamas Dollar (BSD)", Some("BSD")),
    Currency("BTN", "Bhutan Ngultrum (BTN)", Some("BTN")),
    Currency("BWP", "Botswana Pula (BWP)", Some("BWP")),
    Currency("BYN", "Belarus Rouble (BYN)", Some("BYN")),
    Currency("BZD", "Belize Dollar (BZD)", Some("BZD")),
    Currency("CAD", "Canada Dollar (CAD)", Some("CAD")),
    Currency("CDF", "Congo (DemRep) Congo Fr (CDF)", Some("CDF")),
    Currency("CHF", "Switzerland Franc (CHF)", Some("CHF")),
    Currency("CLP", "Chile Peso (CLP)", Some("CLP")),
    Currency("CNY", "China Yuan (CNY)", Some("CNY")),
    Currency("COP", "Colombia Peso (COP)", Some("COP")),
    Currency("CRC", "Costa Rica Colon (CRC)", Some("CRC")),
    Currency("CUP", "Cuba Peso (CUP)", Some("CUP")),
    Currency("CVE", "Cape Verde Islands Escudo (CVE)", Some("CVE")),
    Currency("CZK", "Czech Republic Koruna (CZK)", Some("CZK")),
    Currency("DJF", "Djibouti Franc (DJF)", Some("DJF")),
    Currency("DKK", "Denmark Krone (DKK)", Some("DKK")),
    Currency("DOP", "Dominican Republic Peso (DOP)", Some("DOP")),
    Currency("DZD", "Algeria Dinar (DZD)", Some("DZD")),
    Currency("ECS", "Ecuador Dollar (ECS)", Some("ECS")),
    Currency("EGP", "Egypt Pound (EGP)", Some("EGP")),
    Currency("ERN", "Eritrea Nakfa (ERN)", Some("ERN")),
    Currency("ETB", "Ethiopia Birr (ETB)", Some("ETB")),
    Currency("EUR", "Eurozone Euro (EUR)", Some("EUR")),
    Currency("FJD", "Fiji Islands Dollar (FJD)", Some("FJD")),
    Currency("GEL", "Georgia Lari (GEL)", Some("GEL")),
    Currency("GHS", "Ghana Cedi (GHS)", Some("GHS")),
    Currency("GMD", "Gambia Dalasi (GMD)", Some("GMD")),
    Currency("GNF", "Guinea Republic Franc (GNF)", Some("GNF")),
    Currency("GTQ", "Guatemala Quetzal (GTQ)", Some("GTQ")),
    Currency("GYD", "Guyana Dollar (GYD)", Some("GYD")),
    Currency("HKD", "Hong Kong Dollar (HKD)", Some("HKD")),
    Currency("HNL", "Honduras Lempira (HNL)", Some("HNL")),
    Currency("HRK", "Croatia Kuna (HRK)", Some("HRK")),
    Currency("HTG", "Haiti Gourde (HTG)", Some("HTG")),
    Currency("HUF", "Hungary Forint (HUF)", Some("HUF")),
    Currency("IDR", "Indonesia Rupiah (IDR)", Some("IDR")),
    Currency("ILS", "Israel Shekel (ILS)", Some("ILS")),
    Currency("INR", "India Rupee (INR)", Some("INR")),
    Currency("IQD", "Iraq Dinar (IQD)", Some("IQD")),
    Currency("ISK", "Iceland Krona (ISK)", Some("ISK")),
    Currency("JMD", "Jamaica Dollar (JMD)", Some("JMD")),
    Currency("JOD", "Jordan Dinar (JOD)", Some("JOD")),
    Currency("JPY", "Japan Yen (JPY)", Some("JPY")),
    Currency("KES", "Kenya Schilling (KES)", Some("KES")),
    Currency("KGS", "Kyrgyz Republic Som (KGS)", Some("KGS")),
    Currency("KHR", "Cambodia Riel (KHR)", Some("KHR")),
    Currency("KMF", "Comoros Franc (KMF)", Some("KMF")),
    Currency("KRW", "South Korea Won (KRW)", Some("KRW")),
    Currency("KWD", "Kuwait Dinar (KWD)", Some("KWD")),
    Currency("KYD", "Cayman Islands Dollar (KYD)", Some("KYD")),
    Currency("KZT", "Kazakhstan Tenge (KZT)", Some("KZT")),
    Currency("LAK", "Lao People's Dem Rep Kip (LAK)", Some("LAK")),
    Currency("LBP", "Lebanon Pound (LBP)", Some("LBP")),
    Currency("LKR", "Sri Lanka Rupee (LKR)", Some("LKR")),
    Currency("LRD", "Liberia Dollar (LRD)", Some("LRD")),
    Currency("LSL", "Lesotho Loti (LSL)", Some("LSL")),
    Currency("LYD", "Libya Dinar (LYD)", Some("LYD")),
    Currency("MAD", "Morocco Dirham (MAD)", Some("MAD")),
    Currency("MDL", "Moldova Leu (MDL)", Some("MDL")),
    Currency("MGA", "Madagascar Malagasy Ariary (MGA)", Some("MGA")),
    Currency("MKD", "Macedonia Denar (MKD)", Some("MKD")),
    Currency("MMK", "MyanmarKyat (MMK)", Some("MMK")),
    Currency("MNT", "Mongolia Tugrik (MNT)", Some("MNT")),
    Currency("MOP", "Macao Pataca (MOP)", Some("MOP")),
    Currency("MRO", "Mauritania Ouguiya (MRO)", Some("MRO")),
    Currency("MUR", "Mauritius Rupee (MUR)", Some("MUR")),
    Currency("MVR", "Maldive Islands Rufiyaa (MVR)", Some("MVR")),
    Currency("MWK", "Malawi Kwacha (MWK)", Some("MWK")),
    Currency("MXN", "Mexican Peso (MXN)", Some("MXN")),
    Currency("MYR", "Malaysia Ringgit (MYR)", Some("MYR")),
    Currency("MZN", "Mozambique Metical (MZN)", Some("MZN")),
    Currency("NGN", "Nigeria Naira (NGN)", Some("NGN")),
    Currency("NIO", "Nicaragua Gold Cordoba (NIO)", Some("NIO")),
    Currency("NOK", "Norway Norwegian Krone (NOK)", Some("NOK")),
    Currency("NPR", "Nepal Rupee (NPR)", Some("NPR")),
    Currency("NZD", "New Zealand Dollar (NZD)", Some("NZD")),
    Currency("OMR", "Oman Rial (OMR)", Some("OMR")),
    Currency("PAB", "Panama Balboa (PAB)", Some("PAB")),
    Currency("PEN", "Peru New Sol (PEN)", Some("PEN")),
    Currency("PGK", "Papua New Guinea Kina (PGK)", Some("PGK")),
    Currency("PHP", "Philippines Peso (PHP)", Some("PHP")),
    Currency("PKR", "Pakistan Rupee (PKR)", Some("PKR")),
    Currency("PLN", "Poland Zloty (PLN)", Some("PLN")),
    Currency("PYG", "Paraguay Guarani (PYG)", Some("PYG")),
    Currency("QAR", "Qatar Riyal (QAR)", Some("QAR")),
    Currency("RON", "Romania New Leu (RON)", Some("RON")),
    Currency("RSD", "Serbia Dinar (RSD)", Some("RSD")),
    Currency("RUB", "Russia Rouble (RUB)", Some("RUB")),
    Currency("RWF", "Rwanda Franc RWF", Some("RWF")),
    Currency("SAR", "Saudi Arabia Riyal (SAR)", Some("SAR")),
    Currency("SBD", "Soloman Islands Dollar (SBD)", Some("SBD")),
    Currency("SCR", "Seychelles Rupee (SCR)", Some("SCR")),
    Currency("SDG", "Sudan Republic Pound (SDG)", Some("SDG")),
    Currency("SEK", "Sweden Krona (SEK)", Some("SEK")),
    Currency("SGD", "Singapore Dollar (SGD)", Some("SGD")),
    Currency("SLL", "Sierra Leone Leone (SLL)", Some("SLL")),
    Currency("SOS", "Somali Republic Schilling (SOS)", Some("SOS")),
    Currency("SRD", "Surinam Dollar (SRD)", Some("SRD")),
    Currency("STD", "Saotome and Principe Dobra (STD)", Some("STD")),
    Currency("SVC", "El Salvador Colon (SVC)", Some("SVC")),
    Currency("SZL", "Swaziland Lilangeni (SZL)", Some("SZL")),
    Currency("THB", "Thailand Baht (THB)", Some("THB")),
    Currency("TMT", "Turkmenistan New Manat (TMT)", Some("TMT")),
    Currency("TND", "Tunisia Dinar (TND)", Some("TND")),
    Currency("TOP", "Tonga Islands Pa'anga (AUS) (TOP)", Some("TOP")),
    Currency("TRY", "Turkey Turkish Lira (TRY)", Some("TRY")),
    Currency("TTD", "Trinidad/Tobago Dollar (TTD)", Some("TTD")),
    Currency("TWD", "Taiwan Dollar (TWD)", Some("TWD")),
    Currency("TZS", "Tanzania Schilling (TZS)", Some("TZS")),
    Currency("UAH", "Ukraine Hryvnia (UAH)", Some("UAH")),
    Currency("UGX", "Uganda Schilling (UGX)", Some("UGX")),
    Currency("USD", "USA Dollar (USD)", Some("USD")),
    Currency("UYU", "Uruguay Peso (UYU)", Some("UYU")),
    Currency("UZS", "Uzbekistan Sum (UZS)", Some("UZS")),
    Currency("VEF", "Venezuela Bolivar Fuerte (VEF)", Some("VEF")),
    Currency("VND", "Vietnam Dong (VND)", Some("VND")),
    Currency("VUV", "Vanuatu Vatu (VUV)", Some("VUV")),
    Currency("WST", "Western Samoa Tala (WST)", Some("WST")),
    Currency("XAF", "Cameroon Republic Central African CFA Franc (XAF)", Some("XAF")),
    Currency("XAF", "Central African CFA Franc (XAF)", Some("XAF")),
    Currency("XAF", "Chad Central African CFA Franc (XAF)", Some("XAF")),
    Currency("XAF", "Congo (Brazaville) Central African CFA Franc (XAF)", Some("XAF")),
    Currency("XAF", "Equatorial Guinea Central African CFA Franc (XAF)", Some("XAF")),
    Currency("XAF", "Gabon Central African CFA Franc (XAF)", Some("XAF")),
    Currency("XCD", "East Caribbean Dollar (XCD)", Some("XCD")),
    Currency("XCD", "Dominica East Caribbean Dollar (XCD)", Some("XCD")),
    Currency("XCD", "Grenada East Caribbean Dollar (XCD)", Some("XCD")),
    Currency("XCD", "Montserrat East Caribbean Dollar (XCD)", Some("XCD")),
    Currency("XCD", "St Christopher and Anguilla East Caribbean Dollar (XCD)", Some("XCD")),
    Currency("XCD", "St Lucia East Caribbean Dollar (XCD)", Some("XCD")),
    Currency("XCD", "St Vincent East Caribbean Dollar (XCD)", Some("XCD")),
    Currency("XOF", "Benin West African CFA Franc (XOF)", Some("XOF")),
    Currency("XOF", "Burkina Faso  West African CFA Franc (XOF)", Some("XOF")),
    Currency("XOF", "Cote d'Ivoire West African CFA Franc (XOF)", Some("XOF")),
    Currency("XOF", "Guinea Bissau West African CFA Franc (XOF)", Some("XOF")),
    Currency("XOF", "Mali Republic West African CFA Franc (XOF)", Some("XOF")),
    Currency("XOF", "Niger Republic  West African CFA Franc (XOF)", Some("XOF")),
    Currency("XOF", "Senegal West African CFA Franc (XOF)", Some("XOF")),
    Currency("XOF", "Togo Republic West African CFA Franc (XOF)", Some("XOF")),
    Currency("XPF", "Fr. Polynesia CFP Franc (XPF)", Some("XPF")),
    Currency("XPF", "New Caledonia CFP Franc (XPF)", Some("XPF")),
    Currency("XPF", "Wallis and Futuna Islands CFP Franc (XPF)", Some("XPF")),
    Currency("YER", "Yemen (Rep of) Rial (YER)", Some("YER")),
    Currency("ZAR", "South Africa Rand (ZAR)", Some("ZAR")),
    Currency("ZMW", "Zambia Kwacha (ZMW)", Some("ZMW")),
    Currency("ZWL", "Zimbabwe Dollar (ZWL)", Some("ZWL")),
    Currency("FKP", "Falkland Island Pound (FKP)", None),
    Currency("GIP", "Gibraltar Pound (GIP)", None),
    Currency("GGP", "Guernsey Pound (GGP)", None),
    Currency("IMP", "Isle of Man Pound (IMP)", None),
    Currency("JEP", "Jersey Pound (JEP)", None),
    Currency("SHP", "Saint Helenian Pound (SHP)", None),
    Currency("GBP", "British Pound (GBP)", None)
  )

  "getAllCurrencies" should {

    val currencyService = app.injector.instanceOf[CurrencyService]

    "return the expected currencies" in {
      currencyService.getAllCurrencies shouldEqual expectedCurrencies
    }
  }
}
